spring:
  config:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegramBot
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: minioBot

minio:
  bucket: images
  url: http://localhost:9000
  accessKey: minio
  secretKey: minio123

logging:
  level:
    ROOT: INFO

app:
  download:
    dir:
      C:\Users\Honor\Desktop\minioBot\src\main\resources\photos