server:
  port: 8189

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegramBot
    password: 1234
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml

#minio:
#  bucket: images
#  url: http://localhost:9000
#  accessKey: minio
#  secretKey: minio123

logging:
  level:
    ROOT: INFO
    level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


app:
  download:
   dir:
     C:\Users\Honor\Desktop\webMinioServerBot\src\main\resources\photos