server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5430/telegramBot
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: create-drop

  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml

logging:
  level:
    ROOT: INFO


app:
  download:
    dir:C:\Users\ЗС\OneDrive\Рабочий стол\28-04-25-otus-java\tgHttpBot\src\main\resources\photos: